#!/usr/bin/env python3
"""Render the Live Listings spotlight section in every brochure from data/listings.py.

Run:
    python tools/apply_listings.py

For each brochure with <!-- LISTINGS START --> ... <!-- LISTINGS END -->
markers, the content between the markers is replaced with the rendered
section. Brochures without markers are skipped (run with --add-markers
to insert them, see README of PB-TEMPLATE.md).

No third-party deps — Python stdlib only.
"""
import os, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from data.listings import LISTINGS  # noqa: E402

BROCHURE_DIR = ROOT / 'Brochures html'

# alias → filename (mirrors sync_brochures.py BROCHURES). Kept here so this
# script stays independent of sync_brochures.py (different concerns).
ALIAS_FILE = {
    'portugal':   'portugal-gv.html',
    'greece':     'greece-rbi_1_2.html',
    'cyprus':     'cyprus-rbi_3_3.html',
    'turkey':     'turkey-cbi_8.html',
    'uae':        'uae-rbi_1_7.html',
    'uk':         'uk-rbi_1 (2).html',
    'malta':      'malta-rbi_1_3.html',
    'stkitts':    'stkitts-nevis.html',
    'thailand':   'thailand-rbi_1 (2).html',
    'newzealand': 'newzealand-rbi_1 (3).html',
    'panama':     'panama-rbi_.html',
    'malaysia':   'malaysia-mm2h.html',
}


def render_card(listing, flag, program_code):
    return (
        '        <article class="listing-card">\n'
        f'          <a class="listing-card-link" href="{listing["url"]}" target="_blank" rel="noopener">\n'
        '            <div class="listing-hero">\n'
        f'              <img src="{listing["image"]}" alt="{listing["image_alt"]}" loading="lazy">\n'
        '              <div class="listing-badges">\n'
        f'                <span class="listing-badge listing-badge-flag">{flag} {listing["badge_city"]}</span>\n'
        f'                <span class="listing-badge listing-badge-eligible">✓ Đủ điều kiện {program_code}</span>\n'
        '              </div>\n'
        f'              <div class="listing-ref">{listing["ref"]}</div>\n'
        '            </div>\n'
        '            <div class="listing-body">\n'
        f'              <div class="listing-brand">Vận hành bởi <strong>{listing["brand"]}</strong> · {listing["brand_owner"]}</div>\n'
        f'              <h3 class="listing-name">{listing["name"]}</h3>\n'
        f'              <div class="listing-location">{listing["location"]}</div>\n'
        '              <div class="listing-stats">\n'
        f'                <div class="listing-stat"><div class="listing-stat-val">{listing["price"]}</div><div class="listing-stat-lbl">Giá Khởi Điểm</div></div>\n'
        f'                <div class="listing-stat"><div class="listing-stat-val">{listing["yield_pct"]}</div><div class="listing-stat-lbl">Gross Yield</div></div>\n'
        f'                <div class="listing-stat"><div class="listing-stat-val">{listing["irr_pct"]}</div><div class="listing-stat-lbl">5-Year IRR</div></div>\n'
        f'                <div class="listing-stat"><div class="listing-stat-val">{listing["handover"]}</div><div class="listing-stat-lbl">Bàn Giao</div></div>\n'
        '              </div>\n'
        f'              <p class="listing-desc">{listing["desc"]}</p>\n'
        '              <div class="listing-cta-row">\n'
        '                <span class="listing-cta-primary">Xem Chi Tiết →</span>\n'
        '              </div>\n'
        '            </div>\n'
        '          </a>\n'
        '        </article>'
    )


def render_placeholder(country_vi, program_code):
    return (
        '        <article class="listing-card listing-card-placeholder">\n'
        '          <div class="listing-placeholder-content">\n'
        '            <div class="listing-placeholder-icon">+</div>\n'
        '            <div class="listing-placeholder-title">Đang Cập Nhật</div>\n'
        f'            <div class="listing-placeholder-sub">Thêm BĐS {country_vi} đủ điều kiện {program_code} sẽ được công bố tại đây trong thời gian tới.</div>\n'
        '            <a class="listing-placeholder-link" href="https://nomadassetcollective.com/property-hub/" target="_blank" rel="noopener">Khám phá Property Hub →</a>\n'
        '          </div>\n'
        '        </article>'
    )


def render_section(alias):
    data = LISTINGS[alias]
    flag         = data['flag']
    country_vi   = data['country_vi']
    program_code = data['program_code']
    listings     = data['listings'][:2]   # max 2 cards

    cards = [render_card(l, flag, program_code) for l in listings]
    while len(cards) < 2:
        cards.append(render_placeholder(country_vi, program_code))

    return (
        '    <!-- LIVE LISTINGS — spotlight section between #02 and #03 (PB template; generated by tools/apply_listings.py) -->\n'
        '    <section class="section section-spotlight" id="listings">\n'
        '      <div class="sec-label">Cơ Hội Đầu Tư Thực Tế</div>\n'
        f'      <h2 class="sec-title">BĐS Đủ Điều Kiện {program_code} — Đang Mở Bán</h2>\n'
        f'      <p class="sec-sub">Đây là tài sản đã được NAC thẩm định, đủ điều kiện cho hồ sơ {program_code} {country_vi} và sẵn sàng giao dịch. Bạn không cần săn tìm — chúng tôi đã chọn lọc.</p>\n'
        '\n'
        '      <div class="listings-grid">\n'
        + '\n'.join(cards) + '\n'
        '      </div>\n'
        '\n'
        '      <div class="listings-footnote">\n'
        f'        <span class="listings-fn-text">NAC chỉ giới thiệu BĐS đã được thẩm định pháp lý độc lập và xác nhận đủ điều kiện {program_code} {country_vi}.</span>\n'
        f'        <a class="listings-fn-link" href="https://nomadassetcollective.com/property-hub/" target="_blank" rel="noopener">Tất cả BĐS đủ điều kiện {program_code} →</a>\n'
        '      </div>\n'
        '    </section>'
    )


MARKER_RE = re.compile(
    r'(    <!-- LISTINGS START -->)(.*?)(    <!-- LISTINGS END -->)',
    re.DOTALL,
)


def apply_one(alias):
    if alias not in LISTINGS:
        return None, 'no data'
    fname = ALIAS_FILE.get(alias)
    if not fname:
        return None, 'no filename mapping'
    path = BROCHURE_DIR / fname
    if not path.exists():
        return None, f'file not found ({fname})'

    html = path.read_text(encoding='utf-8')
    if not MARKER_RE.search(html):
        return None, 'no LISTINGS markers (skipped)'

    rendered = render_section(alias)
    new_html = MARKER_RE.sub(
        lambda m: m.group(1) + '\n' + rendered + '\n    ' + m.group(3).lstrip(),
        html,
    )

    if new_html == html:
        return False, 'already up to date'
    path.write_text(new_html, encoding='utf-8')
    return True, 'updated'


def main():
    aliases = sys.argv[1:] or list(ALIAS_FILE.keys())
    changed = 0
    for alias in aliases:
        ok, msg = apply_one(alias)
        marker = '✓' if ok else ('–' if ok is False else '·')
        print(f'  {marker} {alias:12s} {msg}')
        if ok:
            changed += 1
    print(f'\n{changed} brochure(s) updated.')


if __name__ == '__main__':
    main()
